version: '3.0'

services:
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    hostname: db
    environment:
      POSTGRES_PASSWORD: test

  wait_dbs:
    image: "waisbrot/wait"
    restart: "no"
    environment:
      TARGETS: "db:5432"
      TIMEOUT: 60
    depends_on:
      - db

  create_dbs:
    image: "hbpmip/create-databases:1.0.0"
    restart: "no"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - db

  portalbackend:
    image:  hbpmip/portal-backend:5.0.0-standalone
    restart: "no"
    ports:
      - "8080:8080"
      - "8089:8089"
    environment:
      PORTAL_DB_URL: jdbc:postgresql://db:5432/portal
      PORTAL_DB_SERVER: db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      CONTEXT_PATH: /services
      AUTHENTICATION: 0
      FRONTEND_LOGIN_URL: ${FRONTEND_URL}/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: ${FRONTEND_URL}/home
      FRONTEND_AFTER_LOGOUT_URL: ${FRONTEND_URL}/services/login/hbp
      EXAREME_URL: http://10.128.0.11:9090
      WORKFLOW_URL: http://88.197.53.106:8091/Middleware_API-1.0.0-SNAPSHOT/api
      WORKFLOW_AUTHORIZATION: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJtaXAuaHVtYW5icmFpbnByb2plY3QuZXUiLCJpYXQiOjE1Njg5OTE3NDUsImV4cCI6MTYwMDUyNzc0NSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20ifQ.0R4Qzt9vGuiRr07ZVq5SvVC7thPBD9PIBdJ1WtGRt3vcZIvmsaFtVYerQKpRVP-BXqAIjryp8E-vAUrWQBe2Mg"
      LOGGING_LEVEL_WEB: DEBUG
      LOGGING_LEVEL_HIBERNATE: WARN
      SESSION_TIMEOUT: 2592000
      RELEASE_STAGE: "testing"
      DATACENTER_LOCATION: "$HOST"
      CONTAINER_ORCHESTRATION: "docker-compose"
    depends_on:
      - db
    volumes:
      - ./data:/opt/portal/api

  wait_portal_backend:
    image: "waisbrot/wait"
    restart: "no"
    environment:
      TARGETS: "portalbackend:8080"
      TIMEOUT: 60
    depends_on:
      - portalbackend

  frontend:
    image: hbpmip/portal-frontend:5.0.0-beta.2
    depends_on:
      - portalbackend
    ports:
      - "80:80"
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      MODE: federation
      INSTANCE_NAME: "MIP 5.0 alpha"
      VERSION: "5.0 alpha (Woken 3.0.2, Validation 2.8.0, Backend 5.0.0-alpha, Frontend 5.0.0-alpha)"
      TRACKER_ID: UA-80660232-5
      GALAXY_API_URL: "http://localhost:8090/api"
      GALAXY_APACHE_URL: "http://user:pwd@88.197.53.100/nativeGalaxy"
